### ISSUE TITLE
No module named 'ai_trader' issue

### ISSUE THREAD

**Issue by shilik** [whchien/ai-trader#1]
安裝完測試環境後，執行
python ai_trader/strategy/classic/bbands.py 
結果出現以下錯誤，請問如何調整？

`raceback (most recent call last):
  File "/Volumes/Win11SSD/GitHub/ai-trader/ai_trader/strategy/classic/bbands.py", line 3, in <module>
    from ai_trader.trader import AITrader
ModuleNotFoundError: No module named 'ai_trader'`

![image](https://github.com/whchien/ai-trader/assets/1404868/9df99a75-fe15-4609-a0b1-1524c45819c3)

**Comment by whchien** [comment]
Hi 這是因為當前你執行的 terminal Python path 沒有指定到，可以把當前位置加入到 environment variable：
`export PYTHONPATH=${PWD}
`

**Comment by shilik** [comment]
謝謝您快速的回應，目前已經可以執行了。
